---
  - name: "Settig up local development"
    hosts: localhost
    connection: local 
    tasks:

    - name: Create home folders
      become_user: slash3b
      become: true
      file:
        path: "{{ item }}"
        state: directory
        owner: slash3b
        group: slash3b
      loop:
        - /home/slash3b/Projects
        - /home/slash3b/Downloads
        - /home/slash3b/Pictures
        - /home/slash3b/Documents

    - name: Install software 
      ansible.builtin.apt:
        pkg:
          - tmux
          - tree
          - fish
          - docker
          - docker-compose
          - neovim
          - i3
          - rofi
          - make
          - ripgrep
          - silversearcher-ag
          - gcc
          - pkg-config
      tags: soft

    - name: "Pull .dotfiles from GitHub"
      become_user: slash3b
      become: true
      git:
        repo: https://github.com/slash3b/dotfiles.git
        dest: /home/slash3b/Projects/dotfiles
        version: master
        accept_hostkey: yes
      tags: dotfiles

    - name: "Install dotfiles"
      become_user: slash3b
      become: true
      ansible.builtin.script: /home/slash3b/Projects/dotfiles/init.sh
      tags: dotfiles
      args:
        chdir: /home/slash3b/Projects/dotfiles

    - name: Removing current Go installation
      ansible.builtin.shell: |
        rm -rf /usr/local/go

    - name: Download go 1.18
      become_user: slash3b
      become: true
      ansible.builtin.get_url:
        url: https://go.dev/dl/go1.18.3.linux-amd64.tar.gz
        dest: /tmp

    - name: Move go to /usr/local/go
      ansible.builtin.shell: |
        tar -C /usr/local -xzf /tmp/go1.18.3.linux-amd64.tar.gz
        chown -R slash3b:slash3b /usr/local/go

